### ISSUE TITLE
VS Code - Watch - Error when calling methods of an object 

### ISSUE THREAD

**Issue by mabbadi** [Samsung/netcoredbg#28]
Hi, I have the following problem:
when trying to call inside the watch of VS Code a method, for example `a.GetHashCode()`, I get a `Microsoft.CodeAnalysis.Scripting.CompilationErrorException`. See image below; I have made a series of toy examples to show you the problem. So the question is: does this happen to you as well? If not, how can I get rid of this error? On my windows 10 machine I tried with both: the exe available in the releases link, and the exe generated by compiling netcoredbg on my machine.. 

![a](https://user-images.githubusercontent.com/13328563/61008642-65bc1380-a370-11e9-9604-c49b477a0bf7.JPG)

For a complete error log for the first error in the watch see here below:
```
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (1,1): error CS0103: The name 'p' does not exist in the current context
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at SOS.SymbolReader.EvalExpression(String expr, IntPtr opaque, IntPtr& errorText, Int32& typeId, Int32& size, IntPtr& result)
```

Thanks in advance for the help.

**Comment by mabbadi** [comment]
Any idea?

**Comment by viewizard** [comment]
@mabbadi 
Hi,
I can reproduce this on Linux too. Looks like our debugger don't work proper with "watch", should be fixed. Thanks for your report!
Proper behavior should be same (or at least close) to vsdbg:
![Screenshot_2019-07-15_14-35-07](https://user-images.githubusercontent.com/15098562/61216036-16ca0180-a715-11e9-8d3e-fc3aee90972c.png)

**Comment by mabbadi** [comment]
thanks @viewizard ; any idea when its gonna be fixed? Or how difficult is it to fix?

**Comment by viewizard** [comment]
@mabbadi as I know, this issue was added to proposal list, since we limited in resources right now. Unfortunately, I can't say how difficult it is to fix, since I provide only fast investigation of issue.

The point of issue is code that generate prefix with variables assignment only. This part should be refactored in order to work with globals and method calls.
https://github.com/Samsung/netcoredbg/blob/master/src/debug/netcoredbg/SymbolReader.cs#L1306

**Comment by mabbadi** [comment]
thx @viewizard I am looking forward to finding this bug fixed, as I really need the watch working for a project. If there is a way that I could help please let me know. 

Best

**Comment by mabbadi** [comment]
Hi @viewizard do you have any update regarding this feature?

Best

**Comment by viewizard** [comment]
Hi, @mabbadi, as I known, next year plans still not approved yet.
