### ISSUE TITLE
Invalid control characters in JSON payload

### ISSUE THREAD

**Issue by puremourning** [Samsung/netcoredbg#59]
I'm sorry I don't have any steps to reproduce this, but a vimspector user reported that there was a json parse error in a response from netcoredbg.

The python json package reports `Invalid control character at line/column`. It looks like netcoredbg is returning some unescaped shell sequences in the `console` output.

For example: https://files.gitter.im/5bfc5f15d73408ce4fb023af/dYVd/Screenshot-2021-04-13-at-14.08.57.png

```
2021-04-13 15:39:08,214 - DEBUG - Message received (raw): {"seq":177, "event":"output","type":"event","body":{"category":"stdout","output":"[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]\n      User profile is available. Using '/home/anvba/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.\n"}}
2021-04-13 15:39:08,215 - ERROR - Invalid message received: {"seq":177, "event":"output","type":"event","body":{"category":"stdout","output":"[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]\n      User profile is available. Using '/home/anvba/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.\n"}}
Traceback (most recent call last):
  File "/home/anvba/.vim/plugged/vimspector/python3/vimspector/debug_adapter_connection.py", line 231, in _ReadBody
    message = json.loads( payload )
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 83 (char 82)

```

Full log attached.

[vim_sp_message_line.logs.txt](https://github.com/Samsung/netcoredbg/files/6303927/vim_sp_message_line.logs.txt)

**Comment by puremourning** [comment]
cc @Anvba who reported this.

@Anvba if you have some steps to reproduce, I'm sure the team would appreciate it.

**Comment by viewizard** [comment]
Hmm... this looks like I see the issue:
```
"output":"�[40m�[32minfo�[39m�[22m�[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]\n      User profile is available. Using '/home/anvba/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.\n"
```
need investigate this.

**Comment by kfrolov** [comment]
I think, you might want to add symbols `\000`, `\001`... `\037` here: https://github.com/Samsung/netcoredbg/blob/e23f43930b7f823203d58a5fc2578fd795df0e6a/src/protocols/vscodeprotocol.cpp#L265

Currently only limited set of symbols escaped (`\b\f\n\r\t\"\\`), but looks, you want to escape all non-printable symbols.

But I'm not sure, that exactly all symbols (from 0x00 to 0x20) must be escaped. Looks like this is a but not within netcoredbg, but within python parser.

This is JSON-schema of the protocol: https://microsoft.github.io/debug-adapter-protocol/debugAdapterProtocol.json

"output" field must be a "string", string in JSON must not contain following symbols: `\b\f\n\r\t\"\\`. And exactly this set of symbols escaped during when serializing "output" message in netcoredbg (see a link to source code above).

**Comment by kfrolov** [comment]
I think, real source of the problem is python decoder: https://github.com/Smartling/api-sdk-python/blob/c7d038d5fed718ae55021fd09d9f0e852b96c984/simplejson24/decoder.py#L55

If you have an arguments (link to documentation, which say which characters should be escaped in this case) why we should escape non-printable characters, other than `\b\f\n\r\t\"\\`, I think it's possible just to extend list of escaped characters.

**Comment by puremourning** [comment]
From the [JSON specification](https://tools.ietf.org/html/rfc7159#section-7):

> 7.  Strings
>
> The representation of strings is similar to conventions used in the C
   family of programming languages.  A string begins and ends with
   quotation marks.  All Unicode characters may be placed within the
   quotation marks, except for the characters that must be escaped:
   quotation mark, reverse solidus, and the control characters (U+0000
   through U+001F).

The control characters U+0000 through U+001F include the `^[` sequence (U+001B). (I don't have a normative reference for that, but https://codepoints.net/U+001B?lang=en exists as do many other references, also the ascii value is 1B - 27 for ESC)

**Comment by kfrolov** [comment]
Also I see another problem in your logs:
```
2021-04-13 15:39:13,031 - DEBUG - Message received (raw): Content-Length: 318

{"seq":178,"body":{"module":{"id":"a1ba0b7e-c4ee-422a-969b-0fa65ce80f7f","name":"System.Security.Cryptography.Algorithms.dll","path":"/usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.13/System.Security.Cryptography.Algorithms.dll","symbolStatus":"Symbols not found."},"reason":"new"},"event":"mod
2021-04-13 15:39:13,031 - ERROR - Invalid message received: Content-Length: 318

{"seq":178,"body":{"module":{"id":"a1ba0b7e-c4ee-422a-969b-0fa65ce80f7f","name":"System.Security.Cryptography.Algorithms.dll","path":"/usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.13/System.Security.Cryptography.Algorithms.dll","symbolStatus":"Symbols not found."},"reason":"new"},"event":"mod
Traceback (most recent call last):
  File "/home/anvba/.vim/plugged/vimspector/python3/vimspector/debug_adapter_connection.py", line 231, in _ReadBody
    message = json.loads( payload )
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

{"command": "continue", "arguments": {"threadId": 78982}, "seq": 18, "type": "request"}
2021-04-13 15:39:13,039 - DEBUG - Message received (raw): ule","type":"event"}Content-Length: 318

{"seq":179,"body":{"module":{"id":"746cd8d3-6cbb-4d18-9d12-be0c724ca082","name":"System.Security.Cryptography.Primitives.dll","path":"/usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.13/System.Security.Cryptography.Primitives.dll","symbolStatus":"Symbols not found."},"reason"
2021-04-13 15:39:13,039 - ERROR - Invalid message received: ule","type":"event"}Content-Length: 318
```

Looks like your code not combines parts of messages, which was read from socket, in correct way: first you read only half of the message and was unable to parse it, second time you trying to parse second half of the message. Your parser must collect whole message (`Content-Length` field gives your number of bytes) and only when it can parse it. You must not parse the partial result each time when returning from `recv()` syscall. This syscall might return each time after receiving next portion of data, but this portion might not contain whole message.

**Comment by Anvba** [comment]
@puremourning @viewizard I haven't done something special... 

- Clean Ubuntu 20.04 installation
- .net core sdk 3.1 and 2.1
- nvim
- checkout existing project
- setup vimspector
- press F5

if you need anything just let me know I'll assist as much as I can

**Comment by puremourning** [comment]
But I confess I hadn't seen the node in the DAP spec that suggests that DAP allows things which aren't valid JSON, which I find hard to swallow. Thanks for linking the python internal. Perhaps the json parser can be told to ignore raw escape sequences and we should be ok.

I'm struggling to find the exact part of the DAP spec that says this though. I only see this:

```
							"output": {
								"type": "string",
								"description": "The output to report."
							},
```

There's no problem with the parser other than it messes up if it receives invalid JSON due to an uncaught exception. That snot really the issue here.

**Comment by kfrolov** [comment]
RFC7159 in clause 7 claims, that:

    All Unicode characters may be placed within the quotation marks,
    except for the characters that must be escaped: quotation mark,
    reverse solidus, and the control characters (U+0000 through U+001F).

So it is definitely a bug in netcoredbg. Control characters must be escaped. I think, EscapedString class should operate not with the list of substitution characters (`subst_chars`), but with list of `string_view's`, which will replace any character listed in `forbidden_chars` (this might be retained as characters list).

**Comment by viewizard** [comment]
@Anvba @puremourning could you please test this PR?
