### ISSUE TITLE
 How to run netcoredebug on x86 OS?

### ISSUE THREAD

**Issue by fenixjiang** [Samsung/netcoredbg#76]
What should I do to run netcore debug on x86 system?
I tried to modify the .vcxproj file. In c/c++ -->preprocessor, delete some definitions like AMD64, _TARGET_AMD64_, add _TARGET_X86_=1.
My preprocessor Definitions like this: 

   `%(PreprocessorDefinitions);WIN32;_WINDOWS;_MIDL_USE_GUIDDEF_;FEATURE_DEFAULT_INTERFACES=1;_TARGET_X86_=1;_X86_;_BLD_CLR;DEBUGGING_SUPPORTED;PROFILING_SUPPORTED;_WIN32;WINVER=0x0602;_WIN32_WINNT=0x0602;WIN32_LEAN_AND_MEAN=1;_CRT_SECURE_NO_WARNINGS;EnC_SUPPORTED;FEATURE_APPDOMAIN_RESOURCE_MONITORING;FEATURE_APPX;FEATURE_ARRAYSTUB_AS_IL;FEATURE_MULTICASTSTUB_AS_IL;FEATURE_CODE_VERSIONING;FEATURE_COLLECTIBLE_TYPES;FEATURE_CLASSIC_COMINTEROP;FEATURE_COMINTEROP;FEATURE_COMINTEROP_APARTMENT_SUPPORT;FEATURE_COMINTEROP_UNMANAGED_ACTIVATION;FEATURE_COMINTEROP_WINRT_MANAGED_ACTIVATION;FEATURE_CORECLR;FEATURE_CORESYSTEM;FEATURE_CORRUPTING_EXCEPTIONS;FEATURE_EVENT_TRACE=1;FEATURE_PERFTRACING=1;FEATURE_HIJACK;FEATURE_ICASTABLE;FEATURE_INTEROP_DEBUGGING;FEATURE_ISYM_READER;FEATURE_JUMPSTAMP;FEATURE_LOADER_OPTIMIZATION;FEATURE_MANAGED_ETW;FEATURE_MANAGED_ETW_CHANNELS;FEATURE_MULTICOREJIT;FEATURE_PREJIT;FEATURE_READYTORUN;FEATURE_REJIT;FEATURE_STANDALONE_SN;FEATURE_STRONGNAME_DELAY_SIGNING_ALLOWED;FEATURE_STRONGNAME_MIGRATION;FEATURE_SVR_GC;FEATURE_SYMDIFF;FEATURE_TIERED_COMPILATION;UNIX_AMD64_ABI_ITF;FEATURE_USE_ASM_GC_WRITE_BARRIERS;FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP;FEATURE_VERSIONING_LOG;FEATURE_WIN32_REGISTRY;FEATURE_LEGACYNETCF_DBG_HOST_CONTROL;FEATURE_WINDOWSPHONE;FEATURE_WINMD_RESILIENT;_SECURE_SCL=0;UNICODE;_UNICODE;LOG_TAG="NETCOREDBG";NOMINMAX;CMAKE_INTDIR="Debug"`.

But i get a "Access violation reading" exception in `AsyncHandle& operator*() const { return ops.get(data); }`  at iosystem.h.

**Comment by viewizard** [comment]
As I know, we support only cmake build for Windows and Linux OSes. Could you please provide more information where did you get this .vcxproj file and how you build netcoredbg for Windows x86?

**Comment by fenixjiang** [comment]
I am build for Windows. After executing the cmake command `cmake .. -G "Visual Studio 16 2019"`, there is a solution file `netcoredbg.sln` in the /build directory, and a `netcoredbg.vcxproj` file and other project files in /build/src. These files build a x64 netcoredbg.exe, and works well in x64 os.  Now I need to debug x86 programs in a x64 or x86 system(windows os). So i want build a x86 netcoredbg, and I did the previous attempt to modify the project file.

**Comment by viewizard** [comment]
IMO, you should work with cmake in proper way. For example: https://stackoverflow.com/questions/28350214/how-to-build-x86-and-or-x64-on-windows-from-command-line-with-cmake

Note, cmake script install part copy libdbgshim.so from dotnet you provide (-DDOTNET_DIR) or from default dotnet (if you don't provide -DDOTNET_DIR). Make sure you copy x86 libdbgshim.so.

**Comment by fenixjiang** [comment]
Here is the informations about my build on x86 window OS.  

with **cmake .. -A Win32 -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug**,  I found that the x64 bit dotnet was downloaded during the whole process. In the following log, I marked some informations with **"<====="**.

My system info:

	Host Name:                 DESKTOP-Q5LCGAH
	OS Name:                   Microsoft Windows 10 Pro
	OS Version:                10.0.19042 N/A Build 19042
	OS Manufacturer:           Microsoft Corporation
	OS Configuration:          Standalone Workstation
	OS Build Type:             Multiprocessor Free
	Registered Owner:          appeon
	Registered Organization:
	Product ID:                00330-80000-00000-AA409
	Original Install Date:     1/18/2021, 11:09:27 PM
	System Boot Time:          12/2/2021, 6:21:20 PM
	System Manufacturer:       VMware, Inc.
	System Model:              VMware Virtual Platform
	System Type:               X86-based PC
	Processor(s):              2 Processor(s) Installed.
							   [01]: x64 Family 6 Model 85 Stepping 7 GenuineIntel ~2195 Mhz
							   [02]: x64 Family 6 Model 85 Stepping 7 GenuineIntel ~2195 Mhz


CMake output:

	C:\Work\netcoredbg2.0-43\build>cmake .. -A Win32 -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug
	-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
	remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
	From https://github.com/dotnet/coreclr
	 * branch              release/3.1 -> FETCH_HEAD
	Your branch is up to date with 'origin/release/3.1'.
	Already on 'release/3.1'
	dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
	dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
	dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
	dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

	VERBOSE: dotnet-install: Get-CLIArchitecture-From-Architecture -Architecture "x64" <==============
	VERBOSE: dotnet-install: Get-NormalizedQuality -Quality ""
	VERBOSE: dotnet-install: Normalized quality: ''
	VERBOSE: dotnet-install: Get-NormalizedChannel -Channel "5.0"
	VERBOSE: dotnet-install: Normalized channel: '5.0'
	VERBOSE: dotnet-install: Get-NormalizedProduct -Runtime ""
	VERBOSE: dotnet-install: Normalized product: 'dotnet-sdk'
	VERBOSE: dotnet-install: Get-AkaMSDownloadLink -Channel "5.0" -Quality "" -Internal "False" -Product "dotnet-sdk" -Architecture "x64"
	VERBOSE: dotnet-install: Retrieving primary payload URL from aka.ms link for channel: '5.0', quality: '' product: 'dotnet-sdk', os: 'win',
	architecture: 'x64'.
	VERBOSE: dotnet-install: Constructed aka.ms link: 'https://aka.ms/dotnet/5.0/dotnet-sdk-win-x64.zip'.<==============
	VERBOSE: dotnet-install: Received response:
	StatusCode: 301, ReasonPhrase: 'Moved Permanently', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
	{
	  Request-Context: appId=cid-v1:b47e5e27-bf85-45ba-a97c-0377ce0e5779
	  X-Response-Cache-Status: True
	  Pragma: no-cache
	  Connection: keep-alive
	  Strict-Transport-Security: max-age=31536000 ; includeSubDomains
	  Cache-Control: no-store, no-cache, max-age=0
	  Date: Wed, 15 Dec 2021 06:44:33 GMT
	  Location: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.210/dotnet-sdk-5.0.210-win-x64.zip<==============
	  Server: Kestrel
	  Content-Length: 0
	  Expires: Wed, 15 Dec 2021 06:44:33 GMT
	}
	VERBOSE: dotnet-install: The redirect location retrieved:
	'https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.210/dotnet-sdk-5.0.210-win-x64.zip'.<==============
	VERBOSE: dotnet-install: Received response:
	StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
	{
	  Age: 16613
	  X-Cache: HIT
	  x-ms-blob-type: BlockBlob
	  x-ms-lease-status: unlocked
	  x-ms-request-id: c0ee9a82-001e-00cd-5058-f1cd83000000
	  x-ms-version: 2009-09-19
	  Accept-Ranges: bytes
	  Date: Wed, 15 Dec 2021 06:44:33 GMT
	  ETag: 0x8D9BF0AB00C1C56
	  Server: ECAcc
	  Server: (hkc/BDA1)
	  Content-Length: 193873186
	  Content-MD5: FqFhbwHzDQoFK75TDFQkKw==
	  Content-Type: application/octet-stream
	  Last-Modified: Tue, 14 Dec 2021 14:04:47 GMT
	}
	VERBOSE: dotnet-install: Retrieved primary named payload URL from aka.ms link:
	'https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.210/dotnet-sdk-5.0.210-win-x64.zip'.<==============
	VERBOSE: dotnet-install: Downloading using legacy url will not be attempted.
	VERBOSE: dotnet-install: Version: '5.0.210'.
	VERBOSE: dotnet-install: Get-Product-Version -AzureFeed "https://dotnetcli.azureedge.net/dotnet" -SpecificVersion "5.0.210"
	-PackageDownloadLink "https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.210/dotnet-sdk-5.0.210-win-x64.zip"<==============
	VERBOSE: dotnet-install: Get-Product-Version-Url -Flattened "True" -AzureFeed "https://dotnetcli.azureedge.net/dotnet" -SpecificVersion
	"5.0.210" -PackageDownloadLink "https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.210/dotnet-sdk-5.0.210-win-x64.zip"<==============
	VERBOSE: dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.210/sdk-productVersion.txt
	VERBOSE: dotnet-install: Get-Product-Version-Url -Flattened "False" -AzureFeed "https://dotnetcli.azureedge.net/dotnet" -SpecificVersion
	"5.0.210" -PackageDownloadLink "https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.210/dotnet-sdk-5.0.210-win-x64.zip"
	VERBOSE: dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.210/productVersion.txt
	VERBOSE: dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.210/sdk-productVersion.txt
	VERBOSE: dotnet-install: Product version: '5.0.210'.
	VERBOSE: dotnet-install: Resolve-Installation-Path -InstallDir "C:/Work/netcoredbg2.0-43/.dotnet"
	VERBOSE: dotnet-install: InstallRoot: C:/Work/netcoredbg2.0-43/.dotnet
	VERBOSE: dotnet-install: Is-Dotnet-Package-Installed -InstallRoot "C:/Work/netcoredbg2.0-43/.dotnet" -RelativePathToPackage "sdk"
	-SpecificVersion "5.0.210"
	VERBOSE: dotnet-install: Is-Dotnet-Package-Installed: DotnetPackagePath=C:\Work\netcoredbg2.0-43\.dotnet\sdk\5.0.210
	VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''namespaceName' = root\cimv2,'queryExpression' = SELECT * FROM
	Win32_LogicalDisk WHERE DeviceId='C:','queryDialect' = WQL'.
	VERBOSE: Operation 'Query CimInstances' complete.
	VERBOSE: dotnet-install: Zip path: C:\Users\appeon\AppData\Local\Temp\txso4jlk.sam
	dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.210/dotnet-sdk-5.0.210-win-x64.zip
	dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.210/dotnet-sdk-5.0.210-win-x64.zip
	VERBOSE: dotnet-install: Extract-Dotnet-Package -ZipPath "C:\Users\appeon\AppData\Local\Temp\txso4jlk.sam" -OutPath
	"C:/Work/netcoredbg2.0-43/.dotnet"
	VERBOSE: dotnet-install: Get-List-Of-Directories-And-Versions-To-Unpack-From-Dotnet-Package -Zip "System.IO.Compression.ZipArchive" -OutPath
	 "C:/Work/netcoredbg2.0-43/.dotnet"
	VERBOSE: dotnet-install: Directories to unpack:
	host/fxr/5.0.13/;packs/Microsoft.AspNetCore.App.Ref/5.0.0/;packs/Microsoft.NETCore.App.Host.win-arm/5.0.13/;packs/Microsoft.NETCore.App.Host
	.win-arm64/5.0.13/;packs/Microsoft.NETCore.App.Host.win-x64/5.0.13/;packs/Microsoft.NETCore.App.Host.win-x86/5.0.13/;packs/Microsoft.NETCore
	.App.Ref/5.0.0/;packs/Microsoft.WindowsDesktop.App.Ref/5.0.0/;packs/NETStandard.Library.Ref/2.1.0/;sdk/5.0.210/;shared/Microsoft.AspNetCore.
	App/5.0.13/;shared/Microsoft.NETCore.App/5.0.13/;shared/Microsoft.WindowsDesktop.App/5.0.13/;templates/5.0.13/
	VERBOSE: dotnet-install: Checking installation: version = 5.0.210
	VERBOSE: dotnet-install: Is-Dotnet-Package-Installed -InstallRoot "C:/Work/netcoredbg2.0-43/.dotnet" -RelativePathToPackage "sdk"
	-SpecificVersion "5.0.210"
	VERBOSE: dotnet-install: Is-Dotnet-Package-Installed: DotnetPackagePath=C:\Work\netcoredbg2.0-43\.dotnet\sdk\5.0.210
	VERBOSE: dotnet-install: The temporary file "C:\Users\appeon\AppData\Local\Temp\txso4jlk.sam" was removed.
	dotnet-install: Adding to current process PATH: "C:\Work\netcoredbg2.0-43\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
	dotnet-install: Note that the script does not resolve dependencies during installation.
	dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install/windows#dependencies
	dotnet-install: Installation finished
	CMake Deprecation Warning at third_party/linenoise-ng/CMakeLists.txt:3 (cmake_minimum_required):
	  Compatibility with CMake < 2.8.12 will be removed from a future version of
	  CMake.

	  Update the VERSION argument <min> value or use a ...<max> suffix to tell
	  CMake that the project does not need compatibility with older versions.


	-- Build mode: Debug
	CMake Warning (dev) at third_party/linenoise-ng/CMakeLists.txt:16 (set):
	  implicitly converting 'path' to 'STRING' type.
	This warning is for project developers.  Use -Wno-dev to suppress it.

	-- Compiler type MSVC: C:/Program Files/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x86/cl.exe
	-- Configuring done
	-- Generating done
	-- Build files have been written to: C:/Work/netcoredbg2.0-43/build

**Comment by fenixjiang** [comment]
In the file fetchdeps.cmake : 51, I modified the `Architecture` to `x86` and then executed CMake `cmake .. -A Win32 -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug`. Now CMake can download the x86 dotnet. and completed build.
but it crashed at `iosystem.h` file` AsyncHandle& operator*() const { return ops.get(data);}`  when it run (Access violation).

I debugged the program but didn't find the problem, can someone help me?

**Comment by alpencolt** [comment]
@fenixjiang are you sure that antivirus and firewall disabled?

**Comment by fenixjiang** [comment]
@alpencolt   Yes. I am sure.   Currently I am running client and netcoredbg(vscode mode) locally.

Will netcoredbg  support 32-bit systems for a long time

**Comment by alpencolt** [comment]
We support only Linux based 32 bit systems. Never tried to run it on Windows 32 bit

**Comment by fenixjiang** [comment]
@alpencolt @viewizard 
I am try to build a x86 netcoredbg in windows 10 x86 OS.
My OS:
     Window 10 version 1903
     32-bit Operationg System, x64-based processor.

In `fetchdeps:line 51`, I change the `-Architecture` from x64 to x86, then cmake build a solution, and build netcoredbg with VS2019 16.11.12.

Everything seem OK, I got a x86 netcoredbg.
But exceptions is throw when i debug it.

![C1](https://user-images.githubusercontent.com/41977643/167107811-67b1ac4f-706e-4c0f-9e86-c2dc9372c048.GIF)
![C2](https://user-images.githubusercontent.com/41977643/167107840-87165432-4c45-4990-b034-08a0f9ebf444.GIF)

With some debug and compare with my x64 netcoredbg, I found `AsyncHandleIterator` is changed in `iosystem_win32.cpp`.

This is `begin` param passed to the function.
![C3](https://user-images.githubusercontent.com/41977643/167108880-8c91b644-f5d1-4f71-a29b-b5a3aed1539e.GIF)

With a stepover, `begin` param is changed where it does not changed in x64 netcoredbg.
![c4](https://user-images.githubusercontent.com/41977643/167109253-538fc7c4-a33c-4ece-99c8-b0915285af33.GIF)

I'm stuck, and i dont know where to start to find the cause of this problem.
Can you give me some suggestions about that exceptions and the 'begin' param changing.

Thanks.

**Comment by viewizard** [comment]
I can only advice you check this case with ASAN. For netcoredbg build with cmake you can only add `-DASAN=1` option.
Note, CoreCLR that also part of netcoredbg process have some ASAN issues, so, test netcoredbg build with ASAN you would need provide some envs, like this:
```
$env:ASAN_OPTIONS = "symbolize=1 handle_sigfpe=0 allow_user_segv_handler=1 use_sigaltstack=0 detect_leaks=0"
```
In case CoreCLR 6.0, you would also need add `alloc_dealloc_mismatch=0` option, since CoreCLR 6.0 have delete/delete[] missmatch issue.

**Comment by fenixjiang** [comment]
@viewizard 

Here is the ASAN log and callstack when run netcoredbg.
It's look like `async_handles` cause the stack buffer underflow, but i don't understand why, it doesn't make sense.


![C5](https://user-images.githubusercontent.com/41977643/167248132-dcc05db9-f1ea-4ccf-80c2-5fbaa62e3aba.GIF)


	== 4880 == ERROR: AddressSanitizer: stack - buffer - underflow on address 0x07cff608 at pc 0x00dab4cb bp 0x07cff578 sp 0x07cff56c
	READ of size 16 at 0x07cff608 thread T1
	== 4880 == WARNING : Failed to use and restart external symbolizer!
	#0 0xdab4e3 in __asan_memcpy D : \a01\_work\2\s\src\vctools\crt\asan\llvm\compiler - rt\lib\asan\asan_interceptors_memintrinsics.cpp:22
	#1 0xd7a8e6 in netcoredbg::IOSystemImpl<netcoredbg::IOSystemTraits<netcoredbg::Win32PlatformTag> >::async_wait C : \Work\netcoredbg_master\src\utils\iosystem.h:159
	#2 0xd7c360 in netcoredbg::IORedirectHelper::worker C : \Work\netcoredbg_master\src\utils\ioredirect.cpp:209
	#3 0xd750ac in std::invoke<void(__thiscall netcoredbg::IORedirectHelper::*)(void), netcoredbg::IORedirectHelper*> C:\Program Files\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\type_traits:1601
	#4 0xd747f3 in std::thread::_Invoke<std::tuple<void(__thiscall netcoredbg::IORedirectHelper::*)(void), netcoredbg::IORedirectHelper*>, 0, 1> C:\Program Files\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\thread:55
	#5 0xe53731 in thread_start<unsigned int(__stdcall*)(void*), 1> minkernel\crts\ucrt\src\appcrt\startup\thread.cpp:97
	#6 0xd9f940 in __asan::AsanThread::ThreadStart D : \a01\_work\2\s\src\vctools\crt\asan\llvm\compiler - rt\lib\asan\asan_thread.cpp:262
	#7 0xd9e51e in asan_thread_start D : \a01\_work\2\s\src\vctools\crt\asan\llvm\compiler - rt\lib\asan\asan_win.cpp:136
	#8 0x77412368 in BaseThreadInitThunk + 0x18 (C:\Windows\System32\KERNEL32.DLL + 0x68922368)
	#9 0x7773e5ca in RtlExpandEnvironmentStrings + 0x20a (C:\Windows\SYSTEM32\ntdll.dll + 0x6a25e5ca)
	#10 0x7773e59e in RtlExpandEnvironmentStrings + 0x1de (C:\Windows\SYSTEM32\ntdll.dll + 0x6a25e59e)

	Address 0x07cff608 is located in stack of thread T1 at offset 0 in frame
	#0 0xd7b73f in netcoredbg::IORedirectHelper::worker C : \Work\netcoredbg_master\src\utils\ioredirect.cpp:126

	This frame has 13 object(s) :
		[16, 96) 'async_handles' <= = Memory access at offset 0 underflows this variable
		[32, 44) 'in_streams'
		[48, 52) 'on_exit'
		[64, 72) 'catch_exit'
		[80, 81) 'dummybuf'
		[96, 116) 'compiler temporary'
		[112, 120) 'read_lock'
		[128, 136) 'compiler temporary'
		[144, 152) 'compiler temporary'
		[160, 180) 'compiler temporary'
		[176, 196) 'compiler temporary'
		[192, 208) 'compiler temporary'
		[208, 224) 'compiler temporary'
		HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
		(longjmp, SEH and C++ exceptions * are * supported)
		Thread T1 created by T0 here :
	#0 0xd9e622 in __asan_wrap_CreateThread D : \a01\_work\2\s\src\vctools\crt\asan\llvm\compiler - rt\lib\asan\asan_win.cpp:145
	#1 0xe53d55 in _beginthreadex minkernel\crts\ucrt\src\appcrt\startup\thread.cpp:209
	#2 0xd74994 in std::thread::_Start<void(__thiscall netcoredbg::IORedirectHelper::*)(void), netcoredbg::IORedirectHelper*> C:\Program Files\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\thread:75
	#3 0xd73c78 in std::thread::thread<void(__thiscall netcoredbg::IORedirectHelper::*)(void), netcoredbg::IORedirectHelper*, 0> C:\Program Files\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\thread:90
	#4 0xd76237 in netcoredbg::IORedirectHelper::IORedirectHelper C : \Work\netcoredbg_master\src\utils\ioredirect.cpp:64
	#5 0xb12f85 in netcoredbg::ManagedDebugger::ManagedDebugger C : \Work\netcoredbg_master\src\debugger\manageddebugger.cpp:174
	#6 0xd7272c in main C : \Work\netcoredbg_master\src\main.cpp:441
	#7 0xe0b822 in invoke_main d : \a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
	#8 0xe0b726 in __scrt_common_main_seh d : \a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
	#9 0xe0b5cc in __scrt_common_main d : \a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
	#10 0xe0b887 in mainCRTStartup d : \a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16
	#11 0x77412368 in BaseThreadInitThunk + 0x18 (C:\Windows\System32\KERNEL32.DLL + 0x68922368)
	#12 0x7773e5ca in RtlExpandEnvironmentStrings + 0x20a (C:\Windows\SYSTEM32\ntdll.dll + 0x6a25e5ca)
	#13 0x7773e59e in RtlExpandEnvironmentStrings + 0x1de (C:\Windows\SYSTEM32\ntdll.dll + 0x6a25e59e)

	SUMMARY: AddressSanitizer: stack - buffer - underflow D : \a01\_work\2\s\src\vctools\crt\asan\llvm\compiler - rt\lib\asan\asan_interceptors_memintrinsics.cpp:22 in __asan_memcpy
	Shadow bytes around the buggy address :
	  0x30f9fe70 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x30f9fe80 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x30f9fe90 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x30f9fea0 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x30f9feb0 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    =>0x30f9fec0 : 00[f1]f1 00 00 00 00 00 00 00 00 00 00 f2 f2 f2
	  0x30f9fed0 : f2 00 04 f2 f2 f2 f2 04 f2 00 f2 01 f2 f8 f8 f8
	  0x30f9fee0 : f2 f2 f2 f2 00 f2 f8 f2 f8 f2 f8 f8 f8 f2 f2 f2
	  0x30f9fef0 : f2 f8 f8 04 f2 f2 f2 f2 00 00 f2 f2 f2 f2 00 00
	  0x30f9ff00 : f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
	  0x30f9ff10 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	Shadow byte legend(one shadow byte represents 8 application bytes) :
		Addressable : 00
		Partially addressable : 01 02 03 04 05 06 07
		Heap left redzone : fa
		Freed heap region : fd
		Stack left redzone : f1
		Stack mid redzone : f2
		Stack right redzone : f3
		Stack after return : f5
		Stack use after scope : f8
		Global redzone : f9
		Global init order : f6
		Poisoned by user : f7
		Container overflow : fc
		Array cookie : ac
		Intra object redzone : bb
		ASan internal:           fe
		Left alloca redzone : ca
		Right alloca redzone : cb
		Shadow gap : cc

**Comment by alpencolt** [comment]
@fenixjiang probably there is bug in [`AsyncHandleIterator`](https://github.com/Samsung/netcoredbg/blob/master/src/utils/iosystem.h#L55) or [`OpsImp`](https://github.com/Samsung/netcoredbg/blob/master/src/utils/iosystem.h#L206) related to win32 or toolchain.
Also handle might be wrong initialized in [`async_read`](https://github.com/Samsung/netcoredbg/blob/master/src/utils/iosystem_win32.cpp#L326).

Probably we'll get access to  32bit Windows and will check issue. Could you publish your changes which allowed to build under Win32? And please share if will get  more details.

**Comment by fenixjiang** [comment]
@alpencolt  
**By modifying the number of alignas**(see the last chang below), I can run the x86 netcoredbg correctly in 32bit Windows OS.  That stack under flow problem does not appear,  i didn't find a reason to explain it, just getting him to run correctly now.

Below are the modifications i made:

 1.   about cmake:
           In `fetchdeps:line 51`, I change the '-Architecture' from `x64` to `x86`.    (This makes installing the correct x86 dotnet during the cmake process.)

 2.  source:
     After `cmake .. -G "Visual Studio 16 2019"`, Open 'netcoredbg.sln' with VS2019. 
         fix warning C4018 that treated as an error in files:
`src/metadata/modules.cpp`; 
`src/protocols/vscodeprotocol.cpp`;
`src/utils/streams.cpp`

 E.g:  `src/metadata/modules.cpp` : line 1221;
 change `if (Tokens.size() > std::numeric_limits<int32_t>::max())`  
 to  `if (Tokens.size() > (size_t)std::numeric_limits<int32_t>::max())`

With above modifications,  we can compile out x86 netcoredbg, As mentioned before, it crashes when running.

**And with following modification, the crash no longer occurs.**
  at file `src/util/iosystem.h`
CHANGE:  `mutable char data alignas(alignof(std::max_align_t)) [MaxIteratorSize]`
TO: `mutable char data alignas(1)[MaxIteratorSize];`

The above are all my modifications, hope can provide some help.

**Comment by viewizard** [comment]
Fixed in upstream. Windows 10 x86 build and work now.
